version : '3.4'

services: 
  frontend1:
    build: 
      context: .
  frontend2:
    build:
      context: .
  lb-frontend-nginx:
    build:
      context: .
      dockerfile: Dockerfile.loadbalance
    depends_on:
      - frontend1
      - frontend2
    ports: 
      - 8081:80

  balancefy:
    build: 
      context: ./root
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - balancefydb
  balancefydb:
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=balancefy
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/mysql
      - ./migration.sql:/docker-entrypoint-initdb.d/migration.sql

volumes:
  db:

networks:
  default:
    driver: bridge
    name: frontend1