version: '3'

networks: 
  default: 
    external: 
      name: balancefynet

services:

# FRONTEND
  frontend1:
    image: ${FRONTEND_IMAGE_VERSION}
    env_file: ../.env
  

  frontend2:
    image: ${FRONTEND_IMAGE_VERSION}
    env_file: ../.env
   

  loadbalance:
    image: nginx:latest
    
    volumes:
      - ../lb/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/balancefy.ddns.net/cert.pem:/etc/nginx/conf.d/cert.pem
      - /etc/letsencrypt/live/balancefy.ddns.net/privkey.pem:/etc/nginx/conf.d/privkey.pem
    depends_on:
      - frontend1
      - frontend2
    ports:
      - 80:80
      - 443:443
